# Generated by Django 5.0.1 on 2024-01-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Classs', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=250)),
            ],
        ),
    ]
