# Generated by Django 5.0.1 on 2024-01-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admissioninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=30)),
                ('regdate', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
